#Defines the language for Travis to build an instance for
language: python

python:
  - "2.7"
  - "2.8"
  - "2.9"
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

#changes directory to sub-directory "crick-it"
before_install:
  - cd crickit

#installs dependencies
install:
  - pip install
  - pip install coverage
  - pip install codecov

#tests both key scripts
script:
  - python PlayCricket.py
  - python simulate.py
  - coverage run simulate.py

#pushes report to codecov for visualization
after_success:
  - codecov