language: python
python:
  - "3.6"
install:
  - pip install
script:
  - py playCricket.py # or py.test for Python versions 3.5 and below
  - python playCricket.py
  - py3 playCricket.py
  - playCricket.py