#Defines the language for Travis to build an instance for
language: python

python:
  - "3.6"

#changes directory to sub-directory "crick-it"
before_install:
  - cd crick-it

#installs dependencies
install:
  - pip install
  - pip install coverage
  - pip install codecov

#tests both key scripts
script:
  - python PlayCricket.py
  - coverage run PlayCricket.py

#pushes report to codecov for visualization
after_success:
  - codecov