language: python
python:
  - "3.6"
install:
  - pip install
  - pip install coverage
  - pip install codecov

script:
  - cd/crick-it
  - python playCricket.py
  - python simulate.py
  - coverage run playCricket.py

after_success:
  - codecov