language: python
python:
  - "3.6"

before_install:
  - cd crick-it

install:
  - pip install
  - pip install coverage
  - pip install codecov

script:
  - python playCricket.py
  - python simulate.py
  - coverage run playCricket.py

after_success:
  - codecov