language: python
python:
  - "3.6"
install:
  - pip install
  - coverage run playCricket.py
  - coverage python playCricket.py

script:
  - python playCricket.py
  - python simulate.py

after_success:
  - codecov