language: python
python:
  - "3.6"
install:
  - pip install

script:
  - python playCricket.py
  - python simulate.py
    - coverage run playCricket.py
  - coverage python playCricket.py


after_success:
  - codecov